R3FRAME_QUOTES: list[str] = [
    "not a second one...",
    "its all about perspective...",
    "now with colors!",
    "simple interfaces, complex tasks...",
    "made with <3",
    "what will you create?",
    "release date? when?",
    "is it... stable yet?",
    "the beauty is in the design!",
    "building something?",
    "on the right branch?",
    "ship it!",
    "another one bites the dust...",
    "moar particles!",
    "come join the discord! (https://discord.gg/kreGBCVsQQ)",
    "d34d0s, wake up!",
    "its al1v3... its al1v3!!",
    "bundle of joy...",
    "a machine, turning game ideas into \"recover files\"...",
    "what have you done!?",
    "take a look inside...",
    "It comes with a poster!",
    "Build with structure.",
    "no! dont look!",
    "someone should see this...",
    "eat your veggies!",
    "isnt this fun?",
    "now lets add multiplayer...",
    "check out r3shape on github! (https://github.com/r3shape)",
    "try typing `r3 playground` in your terminal...",
]